// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216141800_FixDetallePresupuestoForeignKey")]
    partial class FixDetallePresupuestoForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Backend.Models.AfipCondicionIva", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipCondicionesIva");
                });

            modelBuilder.Entity("Backend.Models.AfipConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificadoNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionFiscal")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsProduccion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAfipCondicionIva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngresosBrutosNumero")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioActividades")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimiteMontoConsumidorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoVentaPorDefecto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.HasIndex("IdAfipCondicionIva");

                    b.ToTable("AfipConfiguraciones");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoComprobanteHabilitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAfipConfiguracion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoFactura")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoFactura");

                    b.HasIndex("IdAfipConfiguracion", "IdTipoFactura")
                        .IsUnique();

                    b.ToTable("AfipTiposComprobantesHabilitados");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipTiposDocumentos");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoIva", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipTiposIva");
                });

            modelBuilder.Entity("Backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAfipCondicionIva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdAfipCondicionIva");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Backend.Models.CondicionVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("CondicionesVenta");
                });

            modelBuilder.Entity("Backend.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFactura")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeFormaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("Backend.Models.DetallePresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeFormaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallesPresupuesto");
                });

            modelBuilder.Entity("Backend.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CAEVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteApellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCorreo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDireccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoConcepto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CotizacionMoneda")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaServicioDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaServicioHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimientoPago")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdAfipTipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCondicionVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoFactura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImporteExento")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteNetoGravado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteTributos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAjuste")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CAE")
                        .HasFilter("[CAE] IS NOT NULL");

                    b.HasIndex("IdAfipTipoDocumento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCondicionVenta");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdTipoFactura");

                    b.HasIndex("PuntoVenta", "NumeroComprobante", "IdTipoFactura")
                        .IsUnique()
                        .HasFilter("[NumeroComprobante] IS NOT NULL");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Backend.Models.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsEditable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PorcentajeAjuste")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteApellido")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCorreo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DescontarStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDescontadoStock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCondicionVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdFacturaGenerada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioDescontoStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroPresupuesto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAjuste")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCondicionVenta");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.HasIndex("IdFacturaGenerada");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdUsuarioDescontoStock");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Backend.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend.Models.TipoFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionAfip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesdeAfip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHastaAfip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaActualizacionAfip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAfip")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposFacturas");
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url_imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.AfipConfiguracion", b =>
                {
                    b.HasOne("Backend.Models.AfipCondicionIva", "AfipCondicionIva")
                        .WithMany()
                        .HasForeignKey("IdAfipCondicionIva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipCondicionIva");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoComprobanteHabilitado", b =>
                {
                    b.HasOne("Backend.Models.AfipConfiguracion", "AfipConfiguracion")
                        .WithMany()
                        .HasForeignKey("IdAfipConfiguracion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TipoFactura", "TipoFactura")
                        .WithMany()
                        .HasForeignKey("IdTipoFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipConfiguracion");

                    b.Navigation("TipoFactura");
                });

            modelBuilder.Entity("Backend.Models.Cliente", b =>
                {
                    b.HasOne("Backend.Models.AfipCondicionIva", "AfipCondicionIva")
                        .WithMany()
                        .HasForeignKey("IdAfipCondicionIva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AfipCondicionIva");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.CondicionVenta", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.DetalleFactura", b =>
                {
                    b.HasOne("Backend.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.DetallePresupuesto", b =>
                {
                    b.HasOne("Backend.Models.Presupuesto", "Presupuesto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Presupuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.Factura", b =>
                {
                    b.HasOne("Backend.Models.AfipTipoDocumento", "AfipTipoDocumento")
                        .WithMany()
                        .HasForeignKey("IdAfipTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.CondicionVenta", "CondicionVenta")
                        .WithMany()
                        .HasForeignKey("IdCondicionVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.TipoFactura", "TipoFactura")
                        .WithMany()
                        .HasForeignKey("IdTipoFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipTipoDocumento");

                    b.Navigation("Cliente");

                    b.Navigation("CondicionVenta");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");

                    b.Navigation("FormaPago");

                    b.Navigation("TipoFactura");
                });

            modelBuilder.Entity("Backend.Models.FormaPago", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.HasOne("Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.CondicionVenta", "CondicionVenta")
                        .WithMany()
                        .HasForeignKey("IdCondicionVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Factura", "FacturaGenerada")
                        .WithMany()
                        .HasForeignKey("IdFacturaGenerada")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "UsuarioDescontoStock")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDescontoStock")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("CondicionVenta");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");

                    b.Navigation("FacturaGenerada");

                    b.Navigation("FormaPago");

                    b.Navigation("UsuarioDescontoStock");
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.HasOne("Backend.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Backend.Models.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
