// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302193231_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Backend.Models.AfipCondicionIva", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipCondicionesIva");
                });

            modelBuilder.Entity("Backend.Models.AfipConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificadoNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionFiscal")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsProduccion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAfipCondicionIva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngresosBrutosNumero")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioActividades")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimiteMontoConsumidorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo_Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.HasIndex("IdAfipCondicionIva");

                    b.ToTable("AfipConfiguraciones");
                });

            modelBuilder.Entity("Backend.Models.AfipPuntoVenta", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bloqueado")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmisionTipo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaBaja")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero");

                    b.ToTable("AfipPuntosVenta", (string)null);
                });

            modelBuilder.Entity("Backend.Models.AfipTipoComprobanteHabilitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAfipConfiguracion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoComprobante");

                    b.HasIndex("IdAfipConfiguracion", "IdTipoComprobante")
                        .IsUnique();

                    b.ToTable("AfipTiposComprobantesHabilitados");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipTiposDocumentos");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoIva", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AfipTiposIva");
                });

            modelBuilder.Entity("Backend.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoVenta");

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AfipTipoDocumentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAfipCondicionIva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAfipTipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AfipTipoDocumentoId");

                    b.HasIndex("IdAfipCondicionIva");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Backend.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CAEVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteApellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCorreo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDireccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDocumento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoConcepto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CotizacionMoneda")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaServicioDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaServicioHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimientoPago")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdAfipTipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCondicionVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEstadoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdFacturaAsociada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImporteExento")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteIVA")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteNetoGravado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteTributos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NumeroComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAjuste")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SesionCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CAE")
                        .HasFilter("[CAE] IS NOT NULL");

                    b.HasIndex("IdAfipTipoDocumento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCondicionVenta");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.HasIndex("IdEstadoComprobante");

                    b.HasIndex("IdFacturaAsociada");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdTipoComprobante");

                    b.HasIndex("SesionCajaId");

                    b.HasIndex("PuntoVenta", "NumeroComprobante", "IdTipoComprobante")
                        .IsUnique()
                        .HasFilter("[NumeroComprobante] IS NOT NULL");

                    b.ToTable("Comprobantes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.CondicionVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasVencimiento")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("CondicionesVenta");
                });

            modelBuilder.Entity("Backend.Models.DetalleComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdComprobante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeFormaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdComprobante");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallesComprobante");
                });

            modelBuilder.Entity("Backend.Models.DetallePresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeFormaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallesPresupuesto");
                });

            modelBuilder.Entity("Backend.Models.EstadoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosComprobantes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.FormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsEditable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PorcentajeAjuste")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("Backend.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SesionCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SesionCajaId");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteApellido")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCorreo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DescontarStock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDescontadoStock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdComprobanteGenerado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCondicionVenta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPresupuestoEstado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdUsuarioDescontoStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroPresupuesto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeAjuste")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SesionCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdComprobanteGenerado");

                    b.HasIndex("IdCondicionVenta");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdPresupuestoEstado");

                    b.HasIndex("IdUsuarioDescontoStock");

                    b.HasIndex("SesionCajaId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Backend.Models.PresupuestoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PresupuestoEstados", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCreado_por")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEliminado_por")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockNegro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCreado_por");

                    b.HasIndex("IdEliminado_por");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend.Models.SesionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoApertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoCierreReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontoCierreSistema")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesCaja", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionAfip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDesdeAfip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHastaAfip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaActualizacionAfip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposComprobantes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Eliminado_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url_imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Models.AfipConfiguracion", b =>
                {
                    b.HasOne("Backend.Models.AfipCondicionIva", "AfipCondicionIva")
                        .WithMany()
                        .HasForeignKey("IdAfipCondicionIva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipCondicionIva");
                });

            modelBuilder.Entity("Backend.Models.AfipTipoComprobanteHabilitado", b =>
                {
                    b.HasOne("Backend.Models.AfipConfiguracion", "AfipConfiguracion")
                        .WithMany()
                        .HasForeignKey("IdAfipConfiguracion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.TipoComprobante", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipConfiguracion");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("Backend.Models.Caja", b =>
                {
                    b.HasOne("Backend.Models.AfipPuntoVenta", "AfipPuntoVentaObj")
                        .WithMany()
                        .HasForeignKey("PuntoVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AfipPuntoVentaObj");
                });

            modelBuilder.Entity("Backend.Models.Cliente", b =>
                {
                    b.HasOne("Backend.Models.AfipTipoDocumento", "AfipTipoDocumento")
                        .WithMany()
                        .HasForeignKey("AfipTipoDocumentoId");

                    b.HasOne("Backend.Models.AfipCondicionIva", "AfipCondicionIva")
                        .WithMany()
                        .HasForeignKey("IdAfipCondicionIva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AfipCondicionIva");

                    b.Navigation("AfipTipoDocumento");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.Comprobante", b =>
                {
                    b.HasOne("Backend.Models.AfipTipoDocumento", "AfipTipoDocumento")
                        .WithMany()
                        .HasForeignKey("IdAfipTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.CondicionVenta", "CondicionVenta")
                        .WithMany()
                        .HasForeignKey("IdCondicionVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.EstadoComprobante", "EstadoComprobante")
                        .WithMany()
                        .HasForeignKey("IdEstadoComprobante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Comprobante", "FacturaAsociada")
                        .WithMany()
                        .HasForeignKey("IdFacturaAsociada")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.TipoComprobante", "TipoComprobante")
                        .WithMany()
                        .HasForeignKey("IdTipoComprobante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.AfipPuntoVenta", "AfipPuntoVentaObj")
                        .WithMany()
                        .HasForeignKey("PuntoVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.SesionCaja", "SesionCaja")
                        .WithMany("Comprobantes")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AfipPuntoVentaObj");

                    b.Navigation("AfipTipoDocumento");

                    b.Navigation("Cliente");

                    b.Navigation("CondicionVenta");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");

                    b.Navigation("EstadoComprobante");

                    b.Navigation("FacturaAsociada");

                    b.Navigation("FormaPago");

                    b.Navigation("SesionCaja");

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("Backend.Models.CondicionVenta", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.DetalleComprobante", b =>
                {
                    b.HasOne("Backend.Models.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("IdComprobante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Comprobante");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.DetallePresupuesto", b =>
                {
                    b.HasOne("Backend.Models.Presupuesto", "Presupuesto")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Presupuesto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Backend.Models.FormaPago", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.MovimientoCaja", b =>
                {
                    b.HasOne("Backend.Models.SesionCaja", "SesionCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionCaja");
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.HasOne("Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Comprobante", "ComprobanteGenerado")
                        .WithMany()
                        .HasForeignKey("IdComprobanteGenerado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.CondicionVenta", "CondicionVenta")
                        .WithMany()
                        .HasForeignKey("IdCondicionVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.PresupuestoEstado", "PresupuestoEstado")
                        .WithMany()
                        .HasForeignKey("IdPresupuestoEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "UsuarioDescontoStock")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDescontoStock")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.SesionCaja", "SesionCaja")
                        .WithMany("Presupuestos")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("ComprobanteGenerado");

                    b.Navigation("CondicionVenta");

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");

                    b.Navigation("FormaPago");

                    b.Navigation("PresupuestoEstado");

                    b.Navigation("SesionCaja");

                    b.Navigation("UsuarioDescontoStock");
                });

            modelBuilder.Entity("Backend.Models.Producto", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Creado_por")
                        .WithMany()
                        .HasForeignKey("IdCreado_por")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Eliminado_por")
                        .WithMany()
                        .HasForeignKey("IdEliminado_por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creado_por");

                    b.Navigation("Eliminado_por");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.SesionCaja", b =>
                {
                    b.HasOne("Backend.Models.Caja", "Caja")
                        .WithMany("Sesiones")
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend.Models.Usuario", b =>
                {
                    b.HasOne("Backend.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Backend.Models.Caja", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Backend.Models.Comprobante", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Backend.Models.Presupuesto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Backend.Models.SesionCaja", b =>
                {
                    b.Navigation("Comprobantes");

                    b.Navigation("Movimientos");

                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
